spring:
  datasource:
    url: jdbc:postgresql://db:5432/eecentral
    username: eecentral
    password: eecentral

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080
