spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eecentral
    username: eecentral
    password: eecentral
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
server:
  port: 8080
